apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
  namespace: ${namespace}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ${registry}/meng/helloworld-fastapi:${version}
        ports:
        - containerPort: 8000